.PHONY: clean All

All:
	@echo "----------Building project:[ Proj1 - Debug ]----------"
	@cd "Proj1" && "$(MAKE)" -f  "Proj1.mk"
clean:
	@echo "----------Cleaning project:[ Proj1 - Debug ]----------"
	@cd "Proj1" && "$(MAKE)" -f  "Proj1.mk" clean
